import Link from "next/link";
import Header from "./components/header";
import "./globals.css";
import type { Metadata } from "next";
import CardModal from "./components/cart-modal";
import { ModalContextProvider } from "./components/modal-context";
import CartContextProvider from "./components/cart-context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const NavFooterLink = [
  "Home",
  "About",
  "Terms & Conditions",
  "Shipping & Return Policy",
  "Privacy Policy",
  "FAQ",
];
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="relative bg-neutral-50 text-black ">
        <CartContextProvider>
          <ModalContextProvider>
            <Header />
            <main className="mb-10">{children}</main>
            <footer>
              <div className="mx-auto flex w-full max-w-7xl flex-col gap-6 border-t border-neutral-200 px-6 py-10 text-base md:flex-row md:gap-12 md:px-4 xl:px-0">
                <div>
                  <Link
                    href={""}
                    className="flex items-center gap-2 text-black dark:text-white md:pt-1"
                  >
                    <div className="flex flex-none items-center justify-center border border-neutral-200 bg-white h-[30px] w-[30px] rounded-lg">
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        aria-label="Acme Store logo"
                        viewBox="0 0 32 28"
                        className=" fill-black dark:fill-white h-[10px] w-[10px]"
                      >
                        <path d="M21.5758 9.75769L16 0L0 28H11.6255L21.5758 9.75769Z"></path>
                        <path d="M26.2381 17.9167L20.7382 28H32L26.2381 17.9167Z"></path>
                      </svg>
                    </div>
                    <span className="uppercase">Acme Store</span>
                  </Link>
                </div>
                <nav>
                  <ul>
                    {NavFooterLink.map((footerLink) => (
                      <li className="text-neutral-400 font-medium">
                        <Link
                          href={`/product/${footerLink}`}
                          className="block p-2 text-lg underline-offset-4 hover:text-black hover:underline dark:hover:text-neutral-300 md:inline-block md:text-base"
                        >
                          {footerLink}
                        </Link>
                      </li>
                    ))}
                  </ul>
                </nav>
                <div className="md:ml-auto">
                  <Link
                    className="flex h-8 flex-none items-center justify-center rounded-md border border-neutral-200 bg-white text-xs text-black "
                    href={""}
                  >
                    <span className="px-3">▲</span>
                    <hr className="h-full border-r border-neutral-200 " />
                    <span className="px-3">Deploy</span>
                  </Link>
                </div>
              </div>
              <div className="border-t border-neutral-200 py-5 text-base ">
                <div className="mx-auto flex w-full max-w-7xl flex-col items-center gap-1 px-4 md:flex-row md:gap-0 md:px-4 xl:px-0">
                  <p className="text-neutral-400  font-medium">
                    © 2023 ACME, Inc. All rights reserved.
                  </p>
                  <hr className="mx-4 hidden h-4 w-[1px] border-l border-neutral-400 md:inline-block" />
                  <p className=" font-medium text-neutral-400">
                    Designed in California
                  </p>
                  <div className="md:ml-auto flex">
                    <p className=" text-neutral-400 font-semibold mr-2">
                      Crafted by
                    </p>
                    <Link href={""} className="text-black font-medium ">
                      ▲ Vercel
                    </Link>
                  </div>
                </div>
              </div>
            </footer>
            <CardModal />
          </ModalContextProvider>
        </CartContextProvider>
      </body>
    </html>
  );
}
